# Generated by Django 2.1 on 2019-11-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField()),
                ('date', models.DateTimeField()),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='error_base.AppModel')),
            ],
        ),
    ]
